idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView, ConfigUserListView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^switch_onidc/', views.switch_onidc, name='switch_onidc'),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:config/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config'),
    url(r'^(?:config/list/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config_list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        EditModelView.as_view(), name='update'),
    url(r'^upload/$',
        views.SummernoteUploadAttachment.as_view(), name='upload'),
    url(r'^import/(?P<model>\w+)/$',
        views.ImportExcelView.as_view(), name='import'),
]


if settings.DEBUG:
    urlpatterns += static.static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

idcops_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

PREFIX = getattr(settings, 'SITE_PREFIX', '')
PREFIX = PREFIX.lstrip('/')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^{}'.format(PREFIX), include('idcops.urls')),
]

idcops/lib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from itertools import chain
from django.urls import reverse_lazy
from django.utils import formats, timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ModelDiffMixin(object):
    """
    A model mixin that tracks model fields' values and provide useful API
    to know what fields have been changed.

    The main value is to allow simply changing the values and then saving the
    object only if it is "really changed"
    """

    def __init__(self, *args, **kwargs):
        super(ModelDiffMixin, self).__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        return bool(self.diff)

    @property
    def changed_fields(self):
        return list(self.diff.keys())

    @property
    def get_d1(self):
        return self.__initial

    @property
    def get_d2(self):
        return self._dict

    @property
    def changed_field_names(self):
        data = {}
        for field_name in self.changed_fields:
            field = self._meta.get_field(field_name)
            data[field.name] = field.verbose_name
        return data

    @property
    def _dict(self):
        exclude = ['operator_id', 'creator_id', 'created', 'modified']
        opts = self._meta
        data = {}
        keys = [f.attname for f in opts.fields]
        for f in chain(opts.many_to_many):
            if self.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(
                    self).values_list('pk', flat=True))
        original = {k: self.__dict__.get(k) for k in keys if k not in exclude}
        data.update(**original)
        for key, value in data.items():
            if isinstance(value, timezone.datetime):
                value = formats.localize(timezone.template_localtime(value))
            data.update(**{key: value})
        return data

    def get_field_diff(self, field_name):
        """
        Returns a diff for field if it's changed and None otherwise.
        """
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """
        Saves model and set initial state.
        """
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    class Meta:
        abstract = True


class AbsoluteUrlMixin(object):
    def get_absolute_url(self):
        opts = self._meta
        if opts.proxy:
            opts = opts.concrete_model._meta
        return reverse_lazy(
            'admin:{}_{}_change'.format(
                opts.app_label, opts.model_name
            ), args=(self.pk,)
        )


class NamedMixin(models.Model):
    """Describes an abstract model with a unique ``name`` field."""
    name = models.CharField(_('name'), max_length=255, unique=True)

    class Meta:
        abstract = True
        ordering = ['name']

    def __str__(self):
        return self.name

    class NonUnique(models.Model):
        """Describes an abstract model with a non-unique ``name`` field."""
        name = models.CharField(verbose_name=_("name"), max_length=75)

        class Meta:
            abstract = True
            ordering = ['name']

        def __str__(self):
            return self.name

idcops/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import uuid
import json
import socket
import struct
import ipaddress

from django.db import models, transaction
from django.db.models.fields import BLANK_CHOICE_DASH
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation
)

from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import formats, timezone
from django.utils.encoding import force_text
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from django.views.generic.base import logger
from django.urls import reverse_lazy

# Create your models here.

from idcops.lib.fields import NullableCharField, IPNetwork
from idcops.lib.models import NamedMixin


def upload_to(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    today = timezone.datetime.now().strftime(r'%Y/%m/%d')
    return os.path.join('uploads', today, filename)


EXT_NAMES = (
    'level', 'hidden', 'dashboard', 'metric', 'icon',
    'icon_color', 'default_filters', 'list_display', 'extra_fields'
)

models.options.DEFAULT_NAMES += EXT_NAMES

COLOR_MAPS = (
    ("red", "红色"),
    ("orange", "橙色"),
    ("yellow", "黄色"),
    ("green", "深绿色"),
    ("blue", "蓝色"),
    ("muted", "灰色"),
    ("black", "黑色"),
    ("aqua", "浅绿色"),
    ("gray", "浅灰色"),
    ("navy", "海军蓝"),
    ("teal", "水鸭色"),
    ("olive", "橄榄绿"),
    ("lime", "高亮绿"),
    ("fuchsia", "紫红色"),
    ("purple", "紫色"),
    ("maroon", "褐红色"),
    ("white", "白色"),
    ("light-blue", "暗蓝色"),
)


class Mark(models.Model):
    CHOICES = (
        ('shared', "已共享的"),
        ('pre_share', "预共享的"),
    )
    mark = models.CharField(
        max_length=64, choices=CHOICES,
        blank=True, null=True,
        verbose_name="系统标记", help_text="系统Slug内容标记")

    class Meta:
        level = 0
        hidden = False
        dashboard = False
        metric = ""
        icon = 'fa fa-circle-o'
        icon_color = ''
        default_filters = {'deleted': False}
        list_display = '__all__'
        extra_fields = []
        abstract = True

    @cached_property
    def get_absolute_url(self):
        opts = self._meta
        # if opts.proxy:
        #    opts = opts.concrete_model._meta
        url = reverse_lazy('idcops:detail', args=[opts.model_name, self.pk])
        return url

    @cached_property
    def get_edit_url(self):
        opts = self._meta
        url = reverse_lazy('idcops:update', args=[opts.model_name, self.pk])
        return url

    def title_description(self):
        return self.__str__()


class Creator(models.Model):
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_creator",
        verbose_name="创建人", help_text="该对象的创建人")

    class Meta:
        abstract = True


class Operator(models.Model):
    operator = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_operator",
        blank=True, null=True,
        verbose_name="修改人", help_text="该对象的修改人"
    )

    class Meta:
        abstract = True


class Created(models.Model):
    created = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="创建日期", help_text="该对象的创建日期"
    )

    class Meta:
        abstract = True


class Modified(models.Model):
    modified = models.DateTimeField(
        auto_now=True, verbose_name="修改日期",
        help_text="该对象的修改日期"
    )

    class Meta:
        abstract = True
        ordering = ['-modified']


class Actived(models.Model):
    actived = models.NullBooleanField(
        default=True, verbose_name="已启用",
        help_text="该对象是否为有效资源"
    )

    class Meta:
        abstract = True


class Deleted(models.Model):
    deleted = models.NullBooleanField(
        default=False,
        verbose_name="已删除", help_text="该对象是否已被删除"
    )

    class Meta:
        abstract = True


class Parent(models.Model):
    parent = models.ForeignKey(
        'self',
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_parent",
        verbose_name="父级对象", help_text="该对象的上一级关联对象"
    )

    class Meta:
        abstract = True


class Onidc(models.Model):
    onidc = models.ForeignKey(
        'Idc',
        blank=True, null=True, on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_onidc",
        verbose_name="所属机房", help_text="该资源所属的机房"
    )

    class Meta:
        abstract = True


class Tag(models.Model):
    tags = models.ManyToManyField(
        'Option',
        blank=True, limit_choices_to={'flag__icontains': 'tags'},
        related_name="%(app_label)s_%(class)s_tags",
        verbose_name="通用标签",
        help_text="可拥有多个标签,字段数据来自机房选项"
    )

    class Meta:
        abstract = True


class ClientAble(models.Model):
    client = models.ForeignKey(
        'Client',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_client",
        verbose_name="所属客户",
        help_text="该资源所属的客户信息"
    )

    class Meta:
        abstract = True


class RackAble(models.Model):
    rack = models.ForeignKey(
        'Rack',
        on_delete=models.CASCADE,
        null=True, blank=True,
        related_name="%(app_label)s_%(class)s_rack",
        verbose_name="所属机柜",
        help_text="该资源所属的机柜信息"
    )

    class Meta:
        abstract = True


class Intervaltime(models.Model):
    start_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        verbose_name="开始时间", help_text="该对象限定的开始时间"
    )
    end_time = models.DateTimeField(
        default=timezone.datetime.now, editable=True,
        null=True, blank=True,
        verbose_name="结束时间", help_text="该对象限定的结束时间"
    )

    class Meta:
        abstract = True


class PersonTime(Creator, Created, Operator, Modified):
    class Meta:
        abstract = True


class ActiveDelete(Actived, Deleted):
    class Meta:
        abstract = True


class Contentable(Onidc, Mark, PersonTime, ActiveDelete):
    content_type = models.ForeignKey(
        ContentType,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_('content type'),
        related_name="%(app_label)s_%(class)s_content_type",
        limit_choices_to={'app_label': 'idcops'}
    )
    object_id = models.PositiveIntegerField(
        _('object id'), blank=True, null=True)
    object_repr = GenericForeignKey('content_type', 'object_id')
    content = models.TextField(verbose_name="详细内容", blank=True)

    def __str__(self):
        return force_text(self.object_repr)

    class Meta:
        abstract = True


class Comment(Contentable):
    class Meta(Mark.Meta):
        level = 2
        hidden = getattr(settings, 'HIDDEN_COMMENT_NAVBAR', True)
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "备注信息"


class Configure(Contentable):
    class Meta(Mark.Meta):
        level = 2
        hidden = getattr(settings, 'HIDDEN_CONFIGURE_NAVBAR', True)
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        verbose_name = verbose_name_plural = "用户配置"

    def __str__(self):
        return f"{self.creator}-{self.content_type} : {self.pk}"


class Remark(models.Model):
    comment = GenericRelation(
        'Comment',
        related_name="%(app_label)s_%(class)s_comment",
        verbose_name="备注信息")

    @property
    def remarks(self):
        return self.comment.filter(deleted=False, actived=True)

    class Meta:
        abstract = True


class Syslog(Contentable):
    action_flag = models.CharField(_('action flag'), max_length=32)
    message = models.TextField(_('change message'), blank=True)
    object_desc = models.CharField(
        max_length=128,
        verbose_name="对象描述"
    )
    related_client = models.CharField(
        max_length=128,
        blank=True, null=True,
        verbose_name="关系客户"
    )

    def title_description(self):
        time = formats.localize(timezone.template_localtime(self.created))
        text = f'{time} > {self.creator} > {self.action_flag}了 > {self.content_type}'
        return text

    class Meta(Mark.Meta):
        icon = 'fa fa-history'
        list_display = [
            'created', 'creator', 'action_flag', 'content_type',
            'object_desc', 'related_client', 'message', 'actived',
        ]
        default_permissions = ('view', 'add', 'change', 'delete', 'exports')
        ordering = ['-created', ]
        verbose_name = verbose_name_plural = _('log entries')


class User(AbstractUser, Onidc, Mark, ActiveDelete, Remark):
    slaveidc = models.ManyToManyField(
        'Idc',
        blank=True,
        verbose_name="附属机房",
        related_name="%(app_label)s_%(class)s_slaveidc"
    )
    upper = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        verbose_name="直属上级",
        related_name="%(app_label)s_%(class)s_upper"
    )
    mobile = models.CharField(max_length=16, blank=True, verbose_name="手机号码")
    avatar = models.ImageField(
        upload_to='avatar/%Y/%m/%d',
        default="avatar/default.png",
        verbose_name="头像"
    )
    settings = models.TextField(
        blank=True,
        verbose_name=_("settings"),
        help_text=_("user settings use json format")
    )

    def __str__(self):
        return self.first_name or self.username

    def title_description(self):
        text = f'{self.onidc} > {self.__str__()} '
        return text

idcops/templates/online/detail.html
{% extends 'device/detail.html' %}
{% load app_extras %}
{%block box-tools-extra%}
<div class="btn-group margin-r-5">
  {%if 'idcops.add_online' in perms %}
  <a class="btn btn-default btn-sm" href="/new/online/?rack_id={{object.rack.pk}}">
    <i class="fa fa-server"></i> <span class="hidden-xs"> 新建设备</span>
  </a>
  {%endif%}

  {%if 'idcops.add_rextend' in perms%}
  <a class="btn btn-default btn-sm" href="{%url 'idcops:new' 'rextend'%}?rack_id={{object.rack.pk}}" data-toggle="modal" data-target="#modal-lg-static">
    <i class="fa fa-battery-2"></i><span class="hidden-xs"> 更新电量</span>
  </a>
  {%endif%}
</div>
{%endblock box-tools-extra%}
{% block page-extra %}
{% rack_overview object.rack_id object.units.all %}
{% endblock %}

idcops/templates/online/edit.html
{% extends 'base/edit.html' %}
{% load app_extras %}

{% block page-extra %}
{%if request.GET.rack_id%}
{% rack_overview request.GET.rack_id object.units.all %}
{%else%}
{% rack_overview object.rack_id object.units.all %}
{%endif%}
{% endblock page-extra %}

{% block SubScript %}
<script>
$(document).ready(function (){

//选择机柜跳转
$("#id_rack").change(function(){
  var selected=$(this).children('option:selected').val();
  if (selected > 0){
    document.location.href="?rack_id="+selected+"";
  };
});
//重置该设备的机柜号

{%if request.GET.rack_id%}
  var rack_id = {{request.GET.rack_id}};
  $("#id_rack option[value=rack_id]").attr('selected', true);
  $("#id_rack").val(rack_id).trigger('change.select2');
{%endif%}

});
</script>
{% endblock SubScript %}

idcops/templates/online/import.html
{% extends 'base/detail.html' %}
{% load static %}
{% block title %}批量导入 {{meta.title}}{% endblock %}

{% block main-content %}
<div class="box box-primary">
    {%block box-header%}
    <div class="box-header with-border">
        <h3 class="box-title"> 批量导入{{meta.verbose_name}}</h3>
        <div class="box-tools pull-right">
            <div class="btn-group margin-r-5">
                <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">
                    <i class="fa fa-arrow-circle-o-left"></i><span> 返回上一页</span>
                </button>
            </div>
        </div>
    </div>
    {%endblock box-header%}
    {%block form%}
    <form action="" method="POST" enctype="multipart/form-data" role="form" class="form-horizontal"
        id="{{meta.model_name}}-new">
        {%block box-body%}
        <div class="box-body">
            {% csrf_token %}
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <b>注意事项：</b>
                    <ol>1、日期格式一定是<b class="text-red">字符串</b>: YYYY-MM-DD，例如：2020-06-06，2020-6-6</ol>
                    <ol>2、Excel日期转字符串公式：<b class="text-red">=TEXT(日期单元格, "YYYY-MM-DD")</b>，例如：=TEXT(F3, "YYYY-MM-DD")</ol>
                    <ol>3、U位格式用`|`分割，例如：04，04|06，04|</ol>
                    <ol>4、由于没有采用后台队列的方式，限制每次最多导入500台设备</ol>
                    <!-- <ol>5、按照模板填写好内容后，另存为 <b class="text-red">.csv</b> 格式的文件进行导入</ol> -->
                    <p><a href="{%static 'idcops/file/online_import_template.xlsx'%}">下载导入模板</a></p>
                </div>
                <hr>

                {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                    <div class="help-block">
                        {%if field.field.required%}
                        <span class="text-red">必填</span>
                        {%else%}
                        <span class="text-muted">选填</span>
                        {%endif%}
                        {{ field.help_text|safe}}
                        <div class="text-red">{{ field.errors|safe }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {%endblock box-body%}
        {%block box-footer%}
        <div class="box-footer">
            <button type="button" class="btn btn-default btn-sm" onclick="window.history.go(-1)">取消并返回</button>
            <div class="btn-group pull-right">
                <button type="submit" class="btn btn-primary btn-sm margin-r-5">提交</button>
            </div>
        </div>
        {%endblock box-footer%}
    </form>
    {%endblock form%}
</div>
{% endblock %}

{% block extra-js %}
<script>
    $(document).ready(function () { });
</script>
{% endblock %}

idcops/templates/online/list.html
{% extends 'base/list.html' %}

{% block table-sub-tools %}
{%if can_create%}
<a class="btn btn-default btn-sm margin-r-5" href="{%url 'idcops:import' meta.model_name %}">
    <i class="fa fa-cloud-upload"></i><span class="hidden-xs"> 批量导入</span>
  </a>
{% endif%}
{%if actions%}
{% for a in actions%}
    <button type="submit" disabled="disabled" name="action" value="{{ a.1 }}" class="action-related disabled btn btn-default btn-sm margin-r-5">
       <i class="{{a.2}}"></i><span class="hidden-xs"> {{ a.3 }}</span>
    </button>
{%endfor%}
{%endif%}
{% endblock table-sub-tools %}

idcops/templates/online/new.html
{% extends 'base/new.html' %}
{% load app_extras %}

{% block page-extra %}
{%if request.GET.rack_id%}
{% rack_overview request.GET.rack_id ''%}
{% endif %}
{% endblock page-extra %}

{% block SubScript %}
<script>
$(document).ready(function (){

  $("#id_rack").change(function(){
    var selected=$(this).children('option:selected').val();
    if (selected > 0){
      document.location.href="?rack_id="+selected+"";
    };
  });

  $("#id_pdus label.btn,#id_units label.btn").click(function(){
    $(this).toggleClass('btn-primary');
  });
  
  function sortArray(m,n){return m>n?1:(m<n?-1:0)}

  function checkUnits(array){
    for(var i=1; i<array.length;i++){
      if(Math.abs(parseInt(array[i])-parseInt(array[i-1])) != 1){
        return false;
      }
    }
    return true;
  }

  // usage
  // checkUnits(getUnits());
  function getUnits(){
    var uSelected = document.getElementsByName('units');
    var data = new Array();
    for(var i=0;i<uSelected.length;i++){
      if(uSelected[i].checked==true){
        data.push(uSelected[i].parentNode.innerText);
      }
    }
    return data.sort(sortArray);
  }


});
</script>
{% endblock SubScript %}

idcops/templates/online/print.html
{% extends 'device/print.html' %}

idcops/templates/online/renewal.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block extra-css %}
<link href="{% static 'idcops/css/select2.min.css' %}" type="text/css" media="all" rel="stylesheet">
{% endblock extra-css %}

{% block content-header %}
<h1>{{meta.verbose_name}}
  <small>
    <b class="text-red"> {{queryset.count}} </b>台设备
  </small>
</h1>
{% endblock %}
{% block main-content %}

{% block form %}
<form method="post" class="form">
  {% csrf_token %}
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">请您确认{{action_name}}清单</h3>
      <div class="box-tools pull-right">
        <input type="hidden" name="action" value="{{action}}" />
        <input type="hidden" name="post" value="yes" />
        <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
        <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
          <span>返回列表</span>
        </a>
      </div>
    </div>
    <div class="box-body table-responsive margin-bottom">
      <table id="item-list" class="table table-bordered table-condensed">
        <thead>
          <tr class="active">
            <th width="3%"> #</th>
            <th>设备编号</th>
            <th>所属机柜</th>
            <th>U位范围</th>
            <th>所属客户</th>
            <th>设备SN号</th>
            <th>设备型号</th>
            <th>设备类型</th>
            <th width="15%">过保时间<b class="text-red"> *</b></th>
          </tr>
        </thead>
        <tbody>
          {% for obj in queryset %}
          <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
          <input type="hidden" name="items" value="{{obj.pk}}" />
          <tr class="{% cycle '' 'active' %}">
            <td style="vertical-align:middle;">{{forloop.counter}}.</td>
            <td style="vertical-align:middle;">
              <a data-toggle="modal" data-target="#modal-lg" href="{{obj.get_absolute_url}}">{{obj}}</a>
            </td>
            <td style="vertical-align:middle;">{{obj.rack}}</td>
            <td style="vertical-align:middle;">{{obj.urange}}</td>
            <td style="vertical-align:middle;">{{obj.client}}</td>
            <td style="vertical-align:middle;">{{obj.sn}}</td>
            <td style="vertical-align:middle;">{{obj.model}}</td>
            <td style="vertical-align:middle;">{{obj.style}}</td>
            <td style="vertical-align:middle;">
              <input id="expiry_date-{{obj.pk}}" class="form-control" type="date" name="expiry_date-{{obj.pk}}"
                value="{{obj.expiry_date}}" />
            </td>

          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>

    <div class="box-footer">
      <div class="box-tools pull-right">
        <b>合计：</b><span id="total">{{queryset.count}}</span> 个
      </div>
    </div>
  </div>
</form>
{% endblock form %}
{% endblock main-content %}

{% block extra-js%}
<script type="text/javascript" src="{%static 'idcops/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{%static 'idcops/js/i18n/zh-CN.js' %}"></script>
<script>
  $(document).ready(function () {

    // reset modal cache
    $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
    });

    // Select2
    var Select = $("select");
    if (Select.length != 0) {
      $("select").select2({ language: "zh-CN" });
    }

  });

</script>
{% endblock extra-js%}