idcops/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include, static
from idcops import views
from idcops.list import ListModelView, ConfigUserListView
from idcops.detail import DetailModelView
from idcops.edit import NewModelView, EditModelView

app_name = 'idcops'


accounts_urls = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^password_change/done/$', views.password_change_done,
        name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset, name='password_reset_confirm'),
    url(r'^reset/done/$', views.reset_done, name='password_reset_complete'),
]


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^welcome/', views.welcome, name='welcome'),
    url(r'^switch_onidc/', views.switch_onidc, name='switch_onidc'),
    url(r'^list/zonemap/', views.ZonemapView.as_view(), name='zonemap'),
    url(r'^(?:new/(?P<model>\w+))/$', NewModelView.as_view(), name='new'),
    url(r'^(?:list/(?P<model>\w+))/$', ListModelView.as_view(), name='list'),
    url(r'^(?:config/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config'),
    url(r'^(?:config/list/(?P<model>\w+))/$',
        ConfigUserListView.as_view(), name='config_list'),
    url(r'^(?:detail/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        DetailModelView.as_view(), name='detail'),
    url(r'^(?:update/(?:(?P<model>\w+)-(?P<pk>\d+)))/$',
        EditModelView.as_view(), name='update'),
    url(r'^upload/$',
        views.SummernoteUploadAttachment.as_view(), name='upload'),
    url(r'^import/(?P<model>\w+)/$',
        views.ImportExcelView.as_view(), name='import'),
]


if settings.DEBUG:
    urlpatterns += static.static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static.static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

idcops_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

PREFIX = getattr(settings, 'SITE_PREFIX', '')
PREFIX = PREFIX.lstrip('/')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^{}'.format(PREFIX), include('idcops.urls')),
]

idcops/lib/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from itertools import chain
from django.urls import reverse_lazy
from django.utils import formats, timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ModelDiffMixin(object):
    """
    A model mixin that tracks model fields' values and provide useful API
    to know what fields have been changed.

    The main value is to allow simply changing the values and then saving the
    object only if it is "really changed"
    """

    def __init__(self, *args, **kwargs):
        super(ModelDiffMixin, self).__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        return bool(self.diff)

    @property
    def changed_fields(self):
        return list(self.diff.keys())

    @property
    def get_d1(self):
        return self.__initial

    @property
    def get_d2(self):
        return self._dict

    @property
    def changed_field_names(self):
        data = {}
        for field_name in self.changed_fields:
            field = self._meta.get_field(field_name)
            data[field.name] = field.verbose_name
        return data

    @property
    def _dict(self):
        exclude = ['operator_id', 'creator_id', 'created', 'modified']
        opts = self._meta
        data = {}
        keys = [f.attname for f in opts.fields]
        for f in chain(opts.many_to_many):
            if self.pk is None:
                data[f.name] = []
            else:
                data[f.name] = list(f.value_from_object(
                    self).values_list('pk', flat=True))
        original = {k: self.__dict__.get(k) for k in keys if k not in exclude}
        data.update(**original)
        for key, value in data.items():
            if isinstance(value, timezone.datetime):
                value = formats.localize(timezone.template_localtime(value))
            data.update(**{key: value})
        return data

    def get_field_diff(self, field_name):
        """
        Returns a diff for field if it's changed and None otherwise.
        """
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """
        Saves model and set initial state.
        """
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    class Meta:
        abstract = True


class AbsoluteUrlMixin(object):
    def get_absolute_url(self):
        opts = self._meta
        if opts.proxy:
            opts = opts.concrete_model._meta
        return reverse_lazy(
            'admin:{}_{}_change'.format(
                opts.app_label, opts.model_name
            ), args=(self.pk,)
        )


class NamedMixin(models.Model):
    """Describes an abstract model with a unique ``name`` field."""
    name = models.CharField(_('name'), max_length=255, unique=True)

    class Meta:
        abstract = True
        ordering = ['name']

    def __str__(self):
        return self.name

    class NonUnique(models.Model):
        """Describes an abstract model with a non-unique ``name`` field."""
        name = models.CharField(verbose_name=_("name"), max_length=75)

        class Meta:
            abstract = True
            ordering = ['name']

        def __str__(self):
            return self.name

idcops/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

import os
import json
import time

from django.apps import apps
from django.shortcuts import render
from django.conf import settings
from django.core.management import call_command
from django.contrib import messages
from django.db import transaction
from django.db.models import Max
from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, PasswordChangeDoneView
)
from django.contrib.auth.views import LoginView as LoginView_
from django.contrib.auth.views import PasswordChangeView as PasswordChangeView_
from django.template.loader import render_to_string
from django.utils.translation import templatize, ugettext as _
from django.utils.encoding import force_text
from django.utils.functional import cached_property
from django.utils.module_loading import import_string
from django.urls import reverse_lazy

# Create your views here.
from idcops.actions import construct_model_meta
from idcops.lib.utils import shared_queryset, get_content_type_for_model
from idcops.mixins import BaseRequiredMixin
from idcops.models import (
    Option, Rack, Device, Online,
    Syslog, ContentType, Zonemap, Client,
    Idc, Attachment
)

from idcops.forms import (
    ImportExcelForm, ZonemapNewForm, InitIdcForm
)


class LoginView(LoginView_):

    template_name='accounts/login.html'
    
    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['demo'] = getattr(settings, 'TEST_ENV', False)
        return context

login = LoginView.as_view()



logout = LogoutView.as_view(template_name='accounts/logout.html')

password_reset = PasswordResetView.as_view(
    template_name='accounts/password_reset_form.html',
    email_template_name='accounts/password_reset_email.html',
    subject_template_name='accounts/password_reset_subject.txt',
    success_url=reverse_lazy('idcops:password_reset_done')
)

password_reset_done = PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html'
)

reset = PasswordResetConfirmView.as_view(
    template_name='accounts/password_reset_confirm.html',
    success_url=reverse_lazy('idcops:password_reset_complete')
)

reset_done = PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html'
)


class PasswordChangeView(BaseRequiredMixin, PasswordChangeView_):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('idcops:logout')


password_change = PasswordChangeView.as_view()

password_change_done = PasswordChangeDoneView.as_view(
    template_name='accounts/password_change_done.html'
)


class SummernoteUploadAttachment(BaseRequiredMixin, View):
    def __init__(self):
        super(SummernoteUploadAttachment, self).__init__()

    def get(self, request, *args, **kwargs):
        return JsonResponse({
            'status': 'false',
            'message': _('Only POST method is allowed'),
        }, status=400)

    def post(self, request, *args, **kwargs):
        if not request.FILES.getlist('files'):
            return JsonResponse({
                'status': 'false',
                'message': _('No files were requested'),
            }, status=400)

        # remove unnecessary CSRF token, if found
        kwargs = request.POST.copy()
        kwargs.pop("csrfmiddlewaretoken", None)

        try:
            attachments = []

            for file in request.FILES.getlist('files'):

                # create instance of appropriate attachment class
                attachment = Attachment()

                attachment.onidc = request.user.onidc
                attachment.creator = request.user
                attachment.file = file
                attachment.name = file.name

                if file.size > 1024 * 1024 * 10:
                    return JsonResponse({
                        'status': 'false',
                        'message': _(
                            '''File size exceeds the '''
                            '''limit allowed and cannot be saved'''
                        ),
                    }, status=400)

                # calling save method with attachment parameters as kwargs
                attachment.save(**kwargs)
                attachments.append(attachment)

            return HttpResponse(render_to_string(
                'document/upload_attachment.json', {
                    'attachments': attachments,
                }), content_type='application/json')
        except IOError:
            return JsonResponse({
                'status': 'false',
                'message': _('Failed to save attachment'),
            }, status=500)


class IndexView(BaseRequiredMixin, TemplateView):

    template_name = 'index.html'

    def make_years(self, queryset):
        years = queryset.datetimes('created', 'month')
        if years.count() > 12:
            ranges = years[(years.count()-12):years.count()]
        else:
            ranges = years[:12]
        return ranges

    def make_device_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Device)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['moveup'] = []
        data['moving'] = []
        data['movedown'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            moving = nlogs.filter(
                message__contains='"units"', action_flag="修改").exclude(
                content__contains='"units": [[]').count()
            data['moving'].append(moving)
            moveup = nlogs.filter(action_flag="新增").count()
            data['moveup'].append(moveup)
            cancel_movedown = nlogs.filter(action_flag="取消下架").count()
            movedown = nlogs.filter(action_flag="下架").count()
            data['movedown'].append(movedown-cancel_movedown)
        return data

    def make_rack_dynamic_change(self):
        content_type = ContentType.objects.get_for_model(Rack)
        logs = Syslog.objects.filter(
            onidc_id=self.onidc_id, content_type=content_type)
        data = {}
        data['categories'] = [m.strftime("%Y-%m")
                              for m in self.make_years(logs)]
        data['renew'] = []
        data['release'] = []
        for y in self.make_years(logs):
            nlogs = logs.filter(created__year=y.year, created__month=y.month)
            data['renew'].append(nlogs.filter(action_flag="分配机柜").count())
            data['release'].append(nlogs.filter(action_flag="释放机柜").count())
        return data

    def make_rack_statistics(self):
        data = []
        robjects = Rack.objects.filter(onidc_id=self.onidc_id, actived=True)
        keys = Option.objects.filter(
            flag__in=['Rack-Style', 'Rack-Status'],
            actived=True)
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            query = {
                k.flag.split('-')[1].lower(): k
            }
            c = robjects.filter(**query).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_online_statistics(self):
        data = []
        dobjects = Online.objects.filter(onidc_id=self.onidc_id)
        keys = Option.objects.filter(flag__in=['Device-Style', 'Device-Tags'])
        keys = shared_queryset(keys, self.onidc_id)
        for k in keys:
            d = []
            if k.flag == 'Device-Style':
                c = dobjects.filter(style=k).count()
            else:
                c = dobjects.filter(tags__in=[k]).count()
            if c > 0:
                d.append(force_text(k))
                d.append(c)
            if d:
                data.append(d)
        return data

    def make_state_items(self):
        state_items = [
            {
                'model_name': app._meta.model_name,
                'verbose_name': app._meta.verbose_name,
                'icon': app._meta.icon,
                'icon_color': 'bg-' + app._meta.icon_color,
                'level': app._meta.level,
                'metric': app._meta.metric,
                'count': app.objects.filter(
                    onidc=self.request.user.onidc).filter(
                    **app._meta.default_filters).count(),
            } for app in apps.get_app_config('idcops').get_models() if getattr(
                app._meta,
                'dashboard')]
        return state_items

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['state_items'] = self.make_state_items()
        context['online_statistics'] = self.make_online_statistics()
        context['device_dynamic_change'] = self.make_device_dynamic_change()
        context['rack_statistics'] = self.make_rack_statistics()
        context['rack_dynamic_change'] = self.make_rack_dynamic_change()
        context['demo'] = getattr(settings, 'TEST_ENV', False)
        context['cloud_ad'] = getattr(settings, 'DISPLAY_AD', False)
        return context


class ProfileView(BaseRequiredMixin, TemplateView):

idcops/templates/rack/detail.html
{% extends 'base/detail.html' %}
{% load app_extras %}
{%block box-tools-extra%}
{% if object.actived %}
<div class="btn-group margin-r-5">
  {%if 'idcops.add_online' in perms %}
  <a class="btn btn-default btn-sm" href="/new/online/?rack_id={{object.pk}}">
    <i class="fa fa-server"></i><span class="hidden-xs"> 新建设备</span>
  </a>
  {%endif%}

  {%if 'idcops.add_rextend' in perms%}
  <a class="btn btn-default btn-sm" href="{%url 'idcops:new' 'rextend'%}?rack_id={{object.pk}}" data-toggle="modal" data-target="#modal-lg-static">
    <i class="fa fa-battery-2"></i><span class="hidden-xs"> 更新电量</span>
  </a>
  {%endif%}
</div>
{% endif %}
{%endblock box-tools-extra%}
{% block page-extra %}
{% rack_overview object.id '' %}
{% endblock %}

idcops/templates/rack/distribution.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block extra-css %}
<link href="{% static 'idcops/css/select2.min.css' %}" type="text/css" media="all" rel="stylesheet">
{% endblock extra-css %}

{% block content-header %}
<h1>{{meta.verbose_name}}
<small>
  <b class="text-red"> {{queryset.count}} </b>个机柜
</small>
</h1>
{% endblock %}
{% block main-content %}

{% block form %}
<form method="post" class="form">
  {% csrf_token %}
<div class="box box-warning">
  <div class="box-header with-border">
    <h3 class="box-title">请您确认{{action_name}}清单</h3>
    <div class="box-tools pull-right">
      <input type="hidden" name="action" value="{{action}}" />
      <input type="hidden" name="post" value="yes" />
      <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
      <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
        <span>返回列表</span>
      </a>
    </div>
  </div>
  <div class="box-body table-responsive margin-bottom">
  <table id="item-list" class="table table-bordered table-condensed">
    <thead>
      <tr class="active">
        <th width="3%"> #</th>
        <th>机柜名称</th>
        <th>机柜别名</th>
        <th>所在区域</th>
        <th width="25%">分配客户</th>
        <th width="10%">合同电力(A)</th>
        <th width="10%">到期时间</th>
        <th width="13%">机柜状态</th>
        <th width="13%">机柜类型</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in queryset %}
      <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
      <input type="hidden" name="items" value="{{obj.pk}}" />
      <tr class="{% cycle '' 'active' %}">
        <td style="vertical-align:middle;">{{forloop.counter}}.</td>
        <td style="vertical-align:middle;">
          <a data-toggle="modal" data-target="#modal-lg" href="{{obj.get_absolute_url}}">{{obj}}</a>
        </td>
        <td style="vertical-align:middle;">{{obj.cname}}</td>
        <td style="vertical-align:middle;">{{obj.zone}}</td>
        <td class="clearfix" style="vertical-align:middle;">
          <select name="client-{{obj.pk}}" required class="form-control">
            <option value="">请选择一个客户</option>
            {%for client in clients%}
            <option value="{{client.id}}">{{client}}</option>
            {%endfor%}
          </select>
        </td>

        <td style="vertical-align:middle;">
          <input id="cpower-{{obj.pk}}" required="required" class="form-control" type="number" name="cpower-{{obj.pk}}" value="10" />
        </td>

        <td style="vertical-align:middle;">
          <input id="expiry_date-{{obj.pk}}" class="form-control" type="date" name="expiry_date-{{obj.pk}}" />
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="status-{{obj.pk}}" class="form-control">
            {%for s in status%}
            <option value="{{s.id}}"{%if s.master%}selected{%endif%}>{{s}}</option>
            {%endfor%}
          </select>
        </td>

        <td class="clearfix" style="vertical-align:middle;">
          <select name="style-{{obj.pk}}" class="form-control">
            {%for style in styles%}
            <option value="{{style.id}}"{%if style.master%}selected{%endif%}>{{style}}</option>
            {%endfor%}
          </select>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
  </div>

  <div class="box-footer">
    <div class="box-tools pull-right">
      <b>合计：</b><span id="total">{{queryset.count}}</span> 个
    </div>
  </div>
</div>
</form>
{% endblock form %}
{% endblock main-content %}

{% block extra-js%}
<script type="text/javascript" src="{%static 'idcops/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{%static 'idcops/js/i18n/zh-CN.js' %}"></script>
<script>
$(document).ready(function (){

// reset modal cache
$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});

// Select2
var Select = $("select");
if (Select.length != 0) {
  $("select").select2({language: "zh-CN"});
}

});

</script>
{% endblock extra-js%}

idcops/templates/rack/list.html
{% extends 'base/list.html' %}

{% block table-sub-tools %}
{%if can_create%}
<a class="btn btn-default btn-sm margin-r-5" href="{%url 'idcops:import' meta.model_name %}">
    <i class="fa fa-cloud-upload"></i><span class="hidden-xs"> 批量导入</span>
  </a>
{% endif%}
{%if actions%}
{% for a in actions%}
    <button type="submit" disabled="disabled" name="action" value="{{ a.1 }}" class="action-related disabled btn btn-default btn-sm margin-r-5">
       <i class="{{a.2}}"></i><span class="hidden-xs"> {{ a.3 }}</span>
    </button>
{%endfor%}
{%endif%}
{% endblock table-sub-tools %}

idcops/templates/rack/overview.html
<table id="rack-detail" style="margin:0; padding:0;" class="table table-bordered text-center nowarp table-condensed">
  <thead>
    <tr class="active">
        <th style="width:2%" class="bg-light-blue">U</th>
        <th style="width:16%" class="bg-light-blue">设备编号</th>
        <th style="width:2%" class="bg-light-blue">U</th>
        <th>PDU</th>
        <th>设备SN号</th>
        <th>IP地址</th>
        <th>设备型号</th>
        <th>客户名称</th>
        <th class="no-print">操作</th>
    </tr>
  </thead>
  <tbody>
      {% for u in units %}
      {% if not u.actived %}
        <tr name="hasdevice" {%if u in obj_units%}class="danger"{%else%}class="success"{%endif%}>
          {%with ucount=u.online.units.all%}
          <td style="vertical-align: middle;" class="no-padding bg-light-blue">{{u}}</td>
          {%if not u.repeat%}
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            <a href="{%url 'idcops:detail' 'online' u.online.pk %}">{{u.online.name}}</a>
          </td>
          {%endif%}
          <td style="vertical-align: middle;" class="no-padding bg-light-blue">{{u}}</td>
          {% if not u.repeat %}
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.pdus%}
              {%for pdu in u.online.pdus.all %}
                <span>{{pdu}} </span>
              {%endfor%}
            {%else%}
              <span>未录入 </span>
            {%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">
            {%if u.online.sn|first == '_' %}<span>无法查看</span>{%else%}<span>{{ u.online.sn|upper }}</span>{%endif%}
          </td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.ipaddr}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.model}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding">{{u.online.client}}</td>
          <td style="vertical-align: middle;" rowspan="{{ucount|length}}" class="no-padding no-print">
          <a href="{%url 'idcops:update' 'online' u.online.pk %}">修改</a>
          </td>
          {%endif%}
          {%endwith%}
        </tr>
      {% else %}
        <tr name="nonedevice">
          <td class="no-padding bg-light-blue">{{u}}</td>
          <td class="no-padding"></td>
          <td class="no-padding bg-light-blue">{{u}}</td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding"></td>
          <td class="no-padding no-print"></td>
        </tr>
      {% endif %}
      {% endfor %}
      <tr>
        <td class="no-padding bg-light-blue">-1</td>
        <td class="no-padding bg-light-blue"></td>
        <td class="no-padding bg-light-blue">-1</td>
        <!-- <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding"></td>
        <td class="no-padding no-print"></td> -->
      </tr>
  </tbody>
</table>

idcops/templates/rack/renewal.html
{% extends 'base/base.html' %}
{% load i18n l10n admin_urls static %}
{% load app_extras static %}
{% block extra-css %}
<link href="{% static 'idcops/css/select2.min.css' %}" type="text/css" media="all" rel="stylesheet">
{% endblock extra-css %}

{% block content-header %}
<h1>{{meta.verbose_name}}
  <small>
    <b class="text-red"> {{queryset.count}} </b>个机柜
  </small>
</h1>
{% endblock %}
{% block main-content %}

{% block form %}
<form method="post" class="form">
  {% csrf_token %}
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">请您确认{{action_name}}清单</h3>
      <div class="box-tools pull-right">
        <input type="hidden" name="action" value="{{action}}" />
        <input type="hidden" name="post" value="yes" />
        <input type="submit" class="btn btn-danger btn-sm margin-r-5" value="确定{{action_name}}" />
        <a href="{%url 'idcops:list' meta.model_name%}" class="btn btn-default btn-sm">
          <span>返回列表</span>
        </a>
      </div>
    </div>
    <div class="box-body table-responsive margin-bottom">
      <table id="item-list" class="table table-bordered table-condensed">
        <thead>
          <tr class="active">
            <th width="3%"> #</th>
            <th>机柜名称</th>
            <th>机柜别名</th>
            <th>所在区域</th>
            <th>所属客户</th>
            <th>合同电力(A)</th>
            <th>机柜状态</th>
            <th>机柜类型</th>
            <th width="15%">到期时间<b class="text-red"> *</b></th>
          </tr>
        </thead>
        <tbody>
          {% for obj in queryset %}
          <input type="hidden" name="index" value="{{ obj.pk|unlocalize }}" />
          <input type="hidden" name="items" value="{{obj.pk}}" />
          <tr class="{% cycle '' 'active' %}">
            <td style="vertical-align:middle;">{{forloop.counter}}.</td>
            <td style="vertical-align:middle;">
              <a data-toggle="modal" data-target="#modal-lg" href="{{obj.get_absolute_url}}">{{obj}}</a>
            </td>
            <td style="vertical-align:middle;">{{obj.cname}}</td>
            <td style="vertical-align:middle;">{{obj.zone}}</td>
            <td style="vertical-align:middle;">{{obj.client}}</td>
            <td style="vertical-align:middle;">{{obj.cpower}}</td>
            <td style="vertical-align:middle;">{{obj.status}}</td>
            <td style="vertical-align:middle;">{{obj.style}}</td>
            <td style="vertical-align:middle;">
              <input id="expiry_date-{{obj.pk}}" class="form-control" type="date" name="expiry_date-{{obj.pk}}"
                value="{{obj.expiry_date}}" />
            </td>

          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>

    <div class="box-footer">
      <div class="box-tools pull-right">
        <b>合计：</b><span id="total">{{queryset.count}}</span> 个
      </div>
    </div>
  </div>
</form>
{% endblock form %}
{% endblock main-content %}

{% block extra-js%}
<script type="text/javascript" src="{%static 'idcops/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{%static 'idcops/js/i18n/zh-CN.js' %}"></script>
<script>
  $(document).ready(function () {

    // reset modal cache
    $('body').on('hidden.bs.modal', '.modal', function () {
      $(this).removeData('bs.modal');
    });

    // Select2
    var Select = $("select");
    if (Select.length != 0) {
      $("select").select2({ language: "zh-CN" });
    }

  });

</script>
{% endblock extra-js%}